name: Run Sales Portal API smoke tests

on:
    pull_request:
    workflow_dispatch:

jobs:
    test:
        timeout-minutes: 60
        runs-on: ubuntu-latest
        container:
            image: mcr.microsoft.com/playwright:v1.57.0-noble
        steps:
            - uses: actions/checkout@v4

            - name: Install OpenJDK
              run: |
                  apt-get update
                  apt-get install -y openjdk-17-jre
                  echo "JAVA_HOME=$(dirname $(dirname $(readlink -f $(which java))))" >> $GITHUB_ENV

            - name: Install dependencies
              run: npm ci

            - name: Install Playwright Browsers
              run: npx playwright install --with-deps

            - name: Run tests
              env:
                  REPORT_PATH: allure-report/api-smoke
                  SALES_PORTAL_API_URL: ${{ secrets.SALES_PORTAL_API_URL }}
                  USER_NAME: ${{ secrets.USER_NAME }}
                  USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
                  TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
                  TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
              run: npm run test:api-smoke
              continue-on-error: true

            # подтягиваем старый отчёт из gh-pages
            - name: Checkout gh-pages
              uses: actions/checkout@v4
              with:
                  ref: gh-pages
                  path: gh-pages

            - name: Copy old history into results
              run: |
                  mkdir -p allure-results/history
                  cp -r gh-pages/allure-report/api-smoke/history allure-results/ || true

            - name: Create Allure report
              run: npm run allure-report

            - name: Save Allure report as artifact
              uses: actions/upload-artifact@v4
              with:
                  name: smoke-report
                  path: ./allure-report

            - name: Deploy to GitHub Pages
              if: success()
              uses: peaceiris/actions-gh-pages@v4
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./allure-report
                  destination_dir: allure-report/api-smoke
